---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_eng.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml
  linux64:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/opt_linux64.yml
      debug:
        task: tasks/builds/dbg_linux64.yml
  linux64-mulet:
    platforms:
      - Mulet Linux
    types:
      opt:
        task: tasks/builds/mulet_linux.yml
      debug:
        task: tasks/builds/mulet_linux_dbg.yml

tests:
  cppunit:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_cppunit.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_cppunit_dbg.yml
  crashtest:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_dbg.yml
  crashtest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_e10s_dbg.yml
  gtest:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_gtest.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_gtest_dbg.yml
  jittests:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_jittests.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jittests_dbg.yml
  jsreftest:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_dbg.yml
  jsreftest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_e10s_dbg.yml
  marionette:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_marionette.yml
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_marionette.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_dbg.yml
  marionette-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_e10s_dbg.yml
  gaia-build:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_build_test.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_build_test.yml
  gaia-build-unit:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_build_unit.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_build_unit.yml
  gaia-js-integration:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_gaia_js_integration_tests.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_gaia_js_integration_tests.yml
  gaia-linter:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_linter.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_linter.yml
  gaia-unit:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_gaia_unit.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_gaia_unit.yml
  gaia-unit-oop:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_gaia_unit_oop.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_gaia_unit_oop.yml
  gaia-ui-test-functional:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_e2e_tests.yml
  gaia-ui-test-functional-dsds:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_e2e_dsds_tests.yml
  gaia-ui-test-unit:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_e2e_api_tests.yml
  mochitest:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_mochitests.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_mochitests.yml
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_dbg.yml
  mochitest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_e10s_dbg.yml
  mochitest-a11y:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_a11y.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_a11y_dbg.yml
  mochitest-browser-chrome:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_dbg.yml
  mochitest-browser-chrome-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_e10s_dbg.yml
  mochitest-chrome:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_chrome.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_chrome_dbg.yml
  mochitest-devtools-chrome:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_dt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_dt_dbg.yml
  mochitest-jetpack:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_jetpack.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_jetpack_dbg.yml
  mochitest-media:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media_dbg.yml
  mochitest-media-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media_e10s_dbg.yml
  mochitest-webgl:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_gl.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_gl_dbg.yml
  reftest:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_reftests.yml
      tasks/builds/mulet_linux_dbg.yml:
        task: tasks/tests/mulet_reftests.yml
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_reftest.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_dbg.yml
  reftest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_e10s_dbg.yml
  web-platform-tests:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_dbg.yml
  web-platform-tests-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_e10s_dbg.yml
  web-platform-tests-reftests:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_dbg.yml
  web-platform-tests-reftests-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_e10s.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_e10s_dbg.yml
  xpcshell:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_xpcshell.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_xpcshell_dbg.yml
